const SET_CREATE_INPUT_VALUE = 'SET_CREATE_INPUT_VALUE';
const SET_IS_CREATE_INPUT_VALUE_MAX_LENGTH = 'SET_IS_CREATE_INPUT_VALUE_MAX_LENGTH';
const SET_EDIT_INPUT_VALUE = 'SET_EDIT_INPUT_VALUE';
const SET_IS_EDIT_INPUT_VALUE_MAX_LENGTH = 'SET_IS_EDIT_INPUT_VALUE_MAX_LENGTH';
const SET_TO_DO_ITEMS = 'SET_TO_DO_ITEMS';
const SET_RADIO_VALUE = 'SET_RADIO_VALUE';
const SET_IS_ALL_COMPLETED = 'SET_IS_ALL_COMPLETED';
const SET_HANDLE_ENTER_STATES = 'SET_HANDLE_ENTER_STATES';

export {
  SET_CREATE_INPUT_VALUE,
  SET_IS_CREATE_INPUT_VALUE_MAX_LENGTH,
  SET_EDIT_INPUT_VALUE,
  SET_IS_EDIT_INPUT_VALUE_MAX_LENGTH,
  SET_TO_DO_ITEMS,
  SET_RADIO_VALUE,
  SET_IS_ALL_COMPLETED,
  SET_HANDLE_ENTER_STATES,
};
